[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyGBM6700e"
version = "2.0.1"
authors = [
  { name="Victor NOGUES", email="victor.nogues@etud.polymtl.ca" },
]
description = "Helper libs for the GBM6700E labs"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
Homepage = "https://github.com/vtrno/PyGBM6700E"